vim.keymap.set('n', '<ESC><ESC>', '<cmd>nohlsearch<CR>') -- ハイライトを消す
vim.keymap.set('n', '<C-J>', ':') -- コマンドモードへ移行

-- カーソルの移動
vim.keymap.set('n', '<C-H>', '^')   -- 行頭へ移動
vim.keymap.set('n', '<C-L>', '$')   -- 行末へ移動

-- 検索
vim.keymap.set('n', '<C-K>', '*')   -- 順方向へ検索

-- レジスタ
vim.keymap.set('n', '<C-E>', '"')   -- レジスタを選択

---- ペースト
vim.keymap.set('n', '<C-I><C-I>', 'p')
vim.keymap.set('n', '<C-I>0', '"0p')
vim.keymap.set('n', '<C-I>1', '"1p')
vim.keymap.set('n', '<C-I>2', '"2p')
vim.keymap.set('n', '<C-I>3', '"3p')
vim.keymap.set('n', '<C-I>4', '"4p')
vim.keymap.set('n', '<C-I>5', '"5p')
vim.keymap.set('n', '<C-I>6', '"6p')
vim.keymap.set('n', '<C-I>7', '"7p')
vim.keymap.set('n', '<C-I>8', '"8p')
vim.keymap.set('n', '<C-I>9', '"9p')
vim.keymap.set('n', '<C-I>a', '"ap')
vim.keymap.set('n', '<C-I>b', '"bp')
vim.keymap.set('n', '<C-I>c', '"cp')
vim.keymap.set('n', '<C-I>d', '"dp')
vim.keymap.set('n', '<C-I>e', '"ep')
vim.keymap.set('n', '<C-I>f', '"fp')
vim.keymap.set('n', '<C-I>g', '"gp')
vim.keymap.set('n', '<C-I>h', '"hp')
vim.keymap.set('n', '<C-I>i', '"ip')
vim.keymap.set('n', '<C-I>j', '"jp')
vim.keymap.set('n', '<C-I>k', '"kp')
vim.keymap.set('n', '<C-I>l', '"lp')
vim.keymap.set('n', '<C-I>m', '"mp')
vim.keymap.set('n', '<C-I>n', '"np')
vim.keymap.set('n', '<C-I>o', '"op')
vim.keymap.set('n', '<C-I>p', '"pp')
vim.keymap.set('n', '<C-I>q', '"qp')
vim.keymap.set('n', '<C-I>r', '"rp')
vim.keymap.set('n', '<C-I>s', '"sp')
vim.keymap.set('n', '<C-I>t', '"tp')
vim.keymap.set('n', '<C-I>u', '"up')
vim.keymap.set('n', '<C-I>v', '"vp')
vim.keymap.set('n', '<C-I>w', '"wp')
vim.keymap.set('n', '<C-I>x', '"xp')
vim.keymap.set('n', '<C-I>y', '"yp')
vim.keymap.set('n', '<C-I>z', '"zp')
vim.keymap.set('n', '<C-I>-', '"-p')
vim.keymap.set('n', '<C-I>*', '"*p')
vim.keymap.set('n', '<C-I>+', '"+p')
vim.keymap.set('n', '<C-I>.', '".p')
vim.keymap.set('n', '<C-I>:', '":p')
vim.keymap.set('n', '<C-I>%', '"%p')
vim.keymap.set('n', '<C-I>#', '"#p')
vim.keymap.set('n', '<C-S-I><C-S-I>', 'P')
vim.keymap.set('n', '<C-S-I>0', '"0P')
vim.keymap.set('n', '<C-S-I>1', '"1P')
vim.keymap.set('n', '<C-S-I>2', '"2P')
vim.keymap.set('n', '<C-S-I>3', '"3P')
vim.keymap.set('n', '<C-S-I>4', '"4P')
vim.keymap.set('n', '<C-S-I>5', '"5P')
vim.keymap.set('n', '<C-S-I>6', '"6P')
vim.keymap.set('n', '<C-S-I>7', '"7P')
vim.keymap.set('n', '<C-S-I>8', '"8P')
vim.keymap.set('n', '<C-S-I>9', '"9P')
vim.keymap.set('n', '<C-S-I>a', '"aP')
vim.keymap.set('n', '<C-S-I>b', '"bP')
vim.keymap.set('n', '<C-S-I>c', '"cP')
vim.keymap.set('n', '<C-S-I>d', '"dP')
vim.keymap.set('n', '<C-S-I>e', '"eP')
vim.keymap.set('n', '<C-S-I>f', '"fP')
vim.keymap.set('n', '<C-S-I>g', '"gP')
vim.keymap.set('n', '<C-S-I>h', '"hP')
vim.keymap.set('n', '<C-S-I>i', '"iP')
vim.keymap.set('n', '<C-S-I>j', '"jP')
vim.keymap.set('n', '<C-S-I>k', '"kP')
vim.keymap.set('n', '<C-S-I>l', '"lP')
vim.keymap.set('n', '<C-S-I>m', '"mP')
vim.keymap.set('n', '<C-S-I>n', '"nP')
vim.keymap.set('n', '<C-S-I>o', '"oP')
vim.keymap.set('n', '<C-S-I>p', '"pP')
vim.keymap.set('n', '<C-S-I>q', '"qP')
vim.keymap.set('n', '<C-S-I>r', '"rP')
vim.keymap.set('n', '<C-S-I>s', '"sP')
vim.keymap.set('n', '<C-S-I>t', '"tP')
vim.keymap.set('n', '<C-S-I>u', '"uP')
vim.keymap.set('n', '<C-S-I>v', '"vP')
vim.keymap.set('n', '<C-S-I>w', '"wP')
vim.keymap.set('n', '<C-S-I>x', '"xP')
vim.keymap.set('n', '<C-S-I>y', '"yP')
vim.keymap.set('n', '<C-S-I>z', '"zP')
vim.keymap.set('n', '<C-S-I>-', '"-P')
vim.keymap.set('n', '<C-S-I>*', '"*P')
vim.keymap.set('n', '<C-S-I>+', '"+P')
vim.keymap.set('n', '<C-S-I>.', '".P')
vim.keymap.set('n', '<C-S-I>:', '":P')
vim.keymap.set('n', '<C-S-I>%', '"%P')
vim.keymap.set('n', '<C-S-I>#', '"#P')
